version: 0.1.{build}
image: Visual Studio 2015
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  project: HeboTech.NLF.sln
  verbosity: minimal
test:
  assemblies: '**\*.Test.dll'
artifacts:
- path: HeboTech.NLF\bin\Release\HeboTech.NLF.dll